logging:
  level:
    com.bstlr.starbux: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

server:
  port: ${PORT:8130}
  servlet:
    context-path: /api/starbux

spring:
  jpa:
    properties:
      hibernate.hbm2ddl.auto: "none"
      hibernate.dialect: "org.hibernate.dialect.PostgreSQL95Dialect"
      hibernate.show_sql: false
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.temp.use_jdbc_metadata_defaults: false
  liquibase:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/starbux}
    user: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
    change-log: classpath:/db/changelog/db-changelog.xml
    contexts: ${spring.profiles.active}
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/starbux}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}

app:
  swagger:
    base-package: "com.bstlr.starbux"
    api-info:
      title: "Starbux API Doc"
      description: "Documentation for Starbux Application"
    secure-paths-regex: "/v1.*"
  discount:
    rate-discount: 25
    cost-for-rate-discount: 12
    drink-amount-for-drink-discount: 3